{% set name = "assist" %}
{% set version = "1.1.9" %}
{% set sha256 = "f5e285e1b17d4c07886e290ba12d9df02780bf7493fbeae743d7d5dfe778c85b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #path: /Users/mjuric/projects/github.com/mjuric/assist
  url: https://github.com/mjuric/assist/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # curl -L https://github.com/mjuric/assist/archive/refs/tags/v1.1.5.tar.gz | openssl sha256

build:
  number: 3
  skip: True  # [win]
  script:
  - |
    SUFFIX=$({{ PYTHON }} -c "import distutils.sysconfig as s; print(s.get_config_var('EXT_SUFFIX'))")
    LIBDIR=$({{ PYTHON }} -c "import distutils.sysconfig as s; print(s.get_python_lib())")
    L="$LIBDIR/libassist$SUFFIX"
    echo "BUILDING LIBRARY: $L"
    {{ PYTHON }} -m pip install . --no-deps -vv
    if [[ $(uname) == Darwin ]]; then
      echo "CHECKING LINKED DEPENDENCIES:"
      otool -L "$L"
      if ! otool -L "$L" | grep -q "librebound"; then
        echo "error: librebound not linked"
        /bin/false
      else
        echo "librebound found to be linked, OK!"
      fi
      echo "==="
    fi

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - rebound >=4.4.1                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - numpy
    - rebound >=4.4.1
    - pip
  run:
    - python
    - rebound >=4.4.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - assist

about:
  home: https://github.com/matthewholman/assist
  license: "GPL-3.0-only"
  license_family: GPL
  license_file: LICENSE
  summary: 'ASSIST solar system integrator'
  description: |
    ASSIST is a software package for ephemeris-quality integrations of test
    particles.  ASSIST is an extension of the REBOUND framework and makes
    use of its IAS15 integrator to integrate test particle trajectories in
    the field of the Sun, Moon, planets, and 16 massive asteroids, with the
    positions of the masses coming from the JPL DE441 ephemeris and its
    associated asteroid perturber file.

extra:
  recipe-maintainers:
    - mjuric
    - matthewholman
