{% set name = "assist" %}
{% set version = "1.1.8.1" %}
{% set sha256 = "3a4ffecabc6cac12d2a4ebedf8bdc43d5cdc8b6fb7e91b33d649bb12a11e5955" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #path: /Users/mjuric/projects/github.com/mjuric/assist
  url: https://github.com/mjuric/assist/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # curl -L https://github.com/mjuric/assist/archive/refs/tags/v1.1.5.tar.gz | openssl sha256

build:
  number: 1
  skip: True  # [win]
  script:
  - |
    echo "Variables ========="
    export
    echo "==================="
    {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy 1.24                             # [build_platform != target_platform]
    - rebound >=4.0                          # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - numpy 1.24
    - rebound >=4.0
    - pip
  run:
    - python
    - rebound >=4.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - assist

about:
  home: https://github.com/matthewholman/assist
  license: "GPL-3.0-only"
  license_family: GPL
  license_file: LICENSE
  summary: 'ASSIST solar system integrator'
  description: |
    ASSIST is a software package for ephemeris-quality integrations of test
    particles.  ASSIST is an extension of the REBOUND framework and makes
    use of its IAS15 integrator to integrate test particle trajectories in
    the field of the Sun, Moon, planets, and 16 massive asteroids, with the
    positions of the masses coming from the JPL DE441 ephemeris and its
    associated asteroid perturber file.

extra:
  recipe-maintainers:
    - mjuric
    - matthewholman
